version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=nexty
      - POSTGRES_USER=nexty
      - POSTGRES_PASSWORD=nexty1234
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8081:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
